## FP-Growth Algorithm

### Importing Libraries

In [1]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder 
from mlxtend.frequent_patterns import association_rules
from mlxtend.frequent_patterns import fpgrowth

In [2]:
dataset = [['mbalvi', '5 kilo meters', 'remember to Walk'], ['mbalvi', 'remember to Walk'],
['Divergent', 'Hassan','remember to Walk'], ['mbalvi', 'Five kilo meters'],
['Divergent','Hassan']] 
te = TransactionEncoder()
te_array = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_array, columns=te.columns_)

In [3]:
df

,5 kilo meters,Divergent,Five kilo meters,Hassan,mbalvi,remember to Walk
0,True,False,False,False,True,True
1,False,False,False,False,True,True
2,False,True,False,True,False,True
3,False,False,True,False,True,False
4,False,True,False,True,False,False

In [4]:
dataset

[['mbalvi', '5 kilo meters', 'remember to Walk'],
 ['mbalvi', 'remember to Walk'],
 ['Divergent', 'Hassan', 'remember to Walk'],
 ['mbalvi', 'Five kilo meters'],
 ['Divergent', 'Hassan']]

In [5]:
frequent_itemsets_fp=fpgrowth(df, min_support=0.02, use_colnames=True)

frequent_itemsets_fp=fpgrowth(df, min_support=0.02, use_colnames=True)

In [9]:
#rules_fp = association_rules(frequent_itemsets_fp, metric="confidence", min_threshold=0.8)

rules_fp = association_rules(frequent_itemsets_fp, frequent_itemsets_fp['support'].sum(), metric="confidence", min_threshold=0.8)
rules_fp

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(5 kilo meters),(mbalvi),0.2,0.6,0.2,1.0,1.666667,1.0,0.08,inf,0.50,0.333333,1.0,0.666667
1,(5 kilo meters),(remember to Walk),0.2,0.6,0.2,1.0,1.666667,1.0,0.08,inf,0.50,0.333333,1.0,0.666667
2,"(5 kilo meters, mbalvi)",(remember to Walk),0.2,0.6,0.2,1.0,1.666667,1.0,0.08,inf,0.50,0.333333,1.0,0.666667
3,"(5 kilo meters, remember to Walk)",(mbalvi),0.2,0.6,0.2,1.0,1.666667,1.0,0.08,inf,0.50,0.333333,1.0,0.666667
4,(5 kilo meters),"(mbalvi, remember to Walk)",0.2,0.4,0.2,1.0,2.500000,1.0,0.12,inf,0.75,0.500000,1.0,0.750000
5,(Hassan),(Divergent),0.4,0.4,0.4,1.0,2.500000,1.0,0.24,inf,1.00,1.000000,1.0,1.000000
6,(Divergent),(Hassan),0.4,0.4,0.4,1.0,2.500000,1.0,0.24,inf,1.00,1.000000,1.0,1.000000
7,"(Hassan, remember to Walk)",(Divergent),0.2,0.4,0.2,1.0,2.500000,1.0,0.12,inf,0.75,0.500000,1.0,0.750000
8,"(Divergent, remember to Walk)",(Hassan),0.2,0.4,0.2,1.0,2.500000,1.0,0.12,inf,0.75,0.500000,1.0,0.750000
9,(Five kilo meters),(mbalvi),0.2,0.6,0.2,1.0,1.666667,1.0,0.08,inf,0.50,0.333333,1.0,0.666667

In [10]:
frequent_itemsets_fp

    support                                   itemsets
0       0.6                         (remember to Walk)
1       0.6                                   (mbalvi)
2       0.2                            (5 kilo meters)
3       0.4                                   (Hassan)
4       0.4                                (Divergent)
5       0.2                         (Five kilo meters)
6       0.4                 (mbalvi, remember to Walk)
7       0.2                    (5 kilo meters, mbalvi)
8       0.2          (5 kilo meters, remember to Walk)
9       0.2  (5 kilo meters, mbalvi, remember to Walk)
10      0.2                 (Hassan, remember to Walk)
11      0.4                        (Hassan, Divergent)
12      0.2              (Divergent, remember to Walk)
13      0.2      (Hassan, Divergent, remember to Walk)
14      0.2                 (Five kilo meters, mbalvi)